In [1]:
import pandas as pd
import numpy as np

file_master_1000 = 'data_ranking_end_year.xlsx'
file_partite = 'file_partite_data_parsed_games.xlsx'



# cambiare stringa_nome_excel per altri tornei
master_data = pd.DataFrame()
stringa_nome_excel = 'RANKING_extracted_end_year_desc_games.xlsx'

In [2]:
file_master_1000_read = pd.read_excel( file_master_1000 )
file_master_1000_data = pd.DataFrame( file_master_1000_read )
file_master_1000_data

,Unnamed: 0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
0,2002,HEWITT,AGASSI,SAFIN,FERRERO,MOYA,FEDERER,NOVAK,HENMAN,COSTA,...,ACASUSO,GAMBILL,ENQVIST,MIRNYI,CORIA,SANGUINETTI,MARTIN,BJORKMAN,LJUBICIC,CALLERI
1,2003,RODDICK,FEDERER,FERRERO,AGASSI,CORIA,SCHUETTLER,MOYA,NALBANDIAN,PHILIPPOUSSIS,...,KAFELNIKOV,LJUBICIC,YOUZHNY,DAVYDENKO,SARETTA,STEPANEK,VOLANDRI,ROCHUS,NADAL,SANCHEZ-MUNOZ
2,2004,FEDERER,RODDICK,HEWITT,SAFIN,MOYA,HENMAN,CORIA,AGASSI,NALBANDIAN,...,LLODRA,SCHUETTLER,VOLANDRI,BECK,BERDYCH,RUSEDSKI,MIRNYI,MALISSE,FERRER,ANDREEV
3,2005,FEDERER,NADAL,RODDICK,HEWITT,DAVYDENKO,NALBANDIAN,AGASSI,CORIA,LJUBICIC,...,ACASUSO,ROCHUS,SRICHAPHAN,YOUZHNY,SANGUINETTI,HAAS,MATHIEU,MALISSE,NOVAK,SERRA
4,2006,FEDERER,NADAL,DAVYDENKO,BLAKE,LJUBICIC,RODDICK,ROBREDO,NALBANDIAN,ANCIC,...,MELZER,CLEMENT,MOYA,MASSU,SIMON,MONFILS,FISH,KIEFER,LEE,GICQUEL
5,2007,FEDERER,NADAL,DJOKOVIC,DAVYDENKO,FERRER,RODDICK,GONZALEZ,GASQUET,NALBANDIAN,...,CALLERI,SODERLING,TSONGA,DelPOTRO,MAHUT,MONTANES,KOUBEK,ROCHUS,KIEFER,SEPPI
6,2008,NADAL,FEDERER,DJOKOVIC,MURRAY,DAVYDENKO,TSONGA,SIMON,RODDICK,DelPOTRO,...,BOLELLI,MOYA,BENNETEAU,LJUBICIC,MONTANES,MONACO,KUNITSYN,ACASUSO,TIPSAREVIC,HANESCU
7,2009,FEDERER,NADAL,DJOKOVIC,MURRAY,DelPOTRO,DAVYDENKO,RODDICK,SODERLING,VERDASCO,...,GARCIA,BAGHDATIS,SELA,BLAKE,ZEBALLOS,BENNETEAU,LOPEZ,HANESCU,SEPPI,CUEVAS
8,2010,NADAL,FEDERER,DJOKOVIC,MURRAY,SODERLING,BERDYCH,FERRER,RODDICK,VERDASCO,...,SIMON,GRANOLLERS,DE,BENNETEAU,CHARDY,STAKHOVSKY,STARACE,DOLGOPOLOV,TIPSAREVIC,ROBREDO
9,2011,DJOKOVIC,NADAL,FEDERER,MURRAY,FERRER,TSONGA,BERDYCH,FISH,TIPSAREVIC,...,DAVYDENKO,TOMIC,KOHLSCHREIBER,BAGHDATIS,HAASE,ANDUJAR,LLODRA,FOGNINI,MALISSE,FERRERO
10,2012,DJOKOVIC,FEDERER,MURRAY,NADAL,FERRER,BERDYCH,DelPOTRO,TSONGA,TIPSAREVIC,...,NIEMINEN,ANDUJAR,ISTOMIN,DAVYDENKO,FOGNINI,GOFFIN,PAIRE,DIMITROV,MATOSEVIC,VINOLAS
11,2013,NADAL,DJOKOVIC,FERRER,MURRAY,DelPOTRO,FEDERER,BERDYCH,WAWRINKA,GASQUET,...,BERLOCQ,MONACO,HAASE,STEPANEK,ISTOMIN,QUERREY,ROSOL,ANDUJAR,SOUSA,MAHUT
12,2014,DJOKOVIC,FEDERER,NADAL,WAWRINKA,NISHIKORI,MURRAY,BERDYCH,RAONIC,CILIC,...,ANDUJAR,SOCK,JANOWICZ,MANNARINO,SEPPI,GRANOLLERS,MULLER,YOUZHNY,ISTOMIN,HEWITT
13,2015,DJOKOVIC,MURRAY,FEDERER,WAWRINKA,NADAL,BERDYCH,FERRER,NISHIKORI,GASQUET,...,VESELY,ROBREDO,KLIZAN,CORIC,BEDENE,BAGHDATIS,MANNARINO,YOUNG,VERDASCO,GABASHVILI
14,2016,MURRAY,DJOKOVIC,RAONIC,WAWRINKA,NISHIKORI,CILIC,MONFILS,THIEM,NADAL,...,DelBONIS,VERDASCO,SOUSA,ALMAGRO,EDMUND,KUZNETSOV,PAIRE,CORIC,FOGNINI,FlorianMAYER
15,2017,NADAL,FEDERER,DIMITROV,ZVEREV,THIEM,CILIC,GOFFIN,SOCK,WAWRINKA,...,PAIRE,HAASE,LORENZI,JOHNSON,KHACHANOV,MONFILS,HARRISON,CORIC,BEDENE,EDMUND
16,2018,DJOKOVIC,NADAL,FEDERER,ZVEREV,DelPOTRO,ANDERSON,CILIC,THIEM,NISHIKORI,...,KLIZAN,MANNARINO,JARRY,SOUSA,JAZIRI,EBDEN,DZUMHUR,LAJOVIC,FRITZ,HAASE
17,2019,NADAL,DJOKOVIC,FEDERER,THIEM,MEDVEDEV,TSITSIPAS,ZVEREV,BERRETTINI,BAUTISTA,...,VINOLAS,EVANS,MANNARINO,QUERREY,CUEVAS,ALBOT,TIAFOE,MILLMAN,VERDASCO,LONDERO
18,2020,DJOKOVIC,NADAL,THIEM,MEDVEDEV,FEDERER,TSITSIPAS,ZVEREV,RUBLEV,SCHWARTZMAN,...,NISHIKORI,CILIC,PELLA,KECMANOVIC,KYRGIOS,VINOLAS,GASQUET,EDMUND,SANDGREN,BUBLIK
19,2021,DJOKOVIC,MEDVEDEV,NADAL,TSITSIPAS,THIEM,ZVEREV,RUBLEV,FEDERER,BERRETTINI,...,MANNARINO,LAJOVIC,MILLMAN,KRAJINOVIC,STRUFF,PAIRE,DelBONIS,FUCSOVICS,KECMANOVIC,KORDA

In [3]:
file_partite_read = pd.read_excel( file_partite )
file_partite_data = pd.DataFrame( file_partite_read )
file_partite_data = file_partite_data.sort_values( by='unicode' )
file_partite_data = file_partite_data.loc[ file_partite_data.data_parsed>'2005-01-01' ]
partite = file_partite_data.iloc[:,1]
partite

1830         QRT_GROSJEAN_DAVYDENKO_3_DOHA_2005_HARD_
1831             F_LJUBICIC_FEDERER_3_DOHA_2005_HARD_
1832           SF_DAVYDENKO_FEDERER_3_DOHA_2005_HARD_
1833              SF_COSTA_LJUBICIC_3_DOHA_2005_HARD_
1834              QRT_SANTORO_COSTA_3_DOHA_2005_HARD_
                             ...
14365         QRT_ISNER_O'CONNELL_3_ATLANTA_2021_HARD
14366     SF_NAKASHIMA_RUUSUVUORI_3_ATLANTA_2021_HARD
14367              SF_ISNER_FRITZ_3_ATLANTA_2021_HARD
14368           F_ISNER_NAKASHIMA_3_ATLANTA_2021_HARD
14369    SF_RUUSUVUORI_NAKASHIMA_3_ATLANTA_2021_HARD_
Name: PARTITE, Length: 12540, dtype: object

In [4]:
def ricerca_stringa_in_dataframe_name1( lista_partite, file_slam_data, lista_raccolta_1, anni_prima, LABEL_PLACE ) :
    dict_years = { '2021':19, '2020':18, '2019':17, '2018':16, '2017':15, '2016':14, '2015':13,
                   '2014':12, '2013':11, '2012':10, '2011':9, '2010':8,
                   '2009':7 , '2008':6 , '2007':5 , '2006':4 , '2005':3}
    dict_placements ={'Top5':[1,2,3,4,5],
                      'Top10':[1,2,3,4,5,6,7,8,9,10],
                      'Top15':list( range( 1,16 ) ),
                      'Top20':list( range( 1,21 ) ),
                      'Top25':list( range( 1,26 ) ),
                      'Top30':list( range(1, 31) ),
                      'Top40':list( range(1, 41) ),
                      'Top50':list( range(1, 51) ) }
    for v in lista_partite :
        n1 = v.split("_")[1]
        n2 = v.split("_")[2]
        if '2021' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2021']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
        elif '2020' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2020']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
        elif '2019' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2019']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
        elif '2018' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2018']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 ) 
        elif '2017' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2017']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
        elif '2016' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2016']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
        elif '2015' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2015']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 ) 
        elif '2014' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2014']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
        elif '2013' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2013']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 ) 
        elif '2012' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2012']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
        elif '2011' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2011']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
        elif '2010' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2010']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
        elif '2009' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2009']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
        elif '2008' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2008']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 ) 
        elif '2007' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2007']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
        elif '2006' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2006']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
        elif '2005' in v :
            if n1 in list( file_slam_data.iloc[ dict_years['2005']-anni_prima, list(dict_placements[ LABEL_PLACE ]) ] ):
                lista_raccolta_1.append( 1 )
            else :
                lista_raccolta_1.append( 0 )
                
                
def ricerca_stringa_in_dataframe_name2( lista_partite, file_slam_data, lista_raccolta_2, anni_prima, LABEL_PLACE ) :
    dict_years = { '2021':19, '2020':18, '2019':17, '2018':16, '2017':15, '2016':14, '2015':13,
                   '2014':12, '2013':11, '2012':10, '2011':9, '2010':8,
                   '2009':7 , '2008':6 , '2007':5 , '2006':4 , '2005':3 }
    dict_placements ={'Top5':[1,2,3,4,5],
                      'Top10':[1,2,3,4,5,6,7,8,9,10],
                      'Top15':list( range( 1,16 ) ),
                      'Top20':list( range( 1,21 ) ),
                      'Top25':list( range( 1,26 ) ),
                      'Top30':list( range(1, 31) ),
                      'Top40':list( range(1, 41) ),
                      'Top50':list( range(1, 51) ) }
    for v in lista_partite :
        n1 = v.split("_")[1]
        n2 = v.split("_")[2]
        if '2021' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2021']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2020' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2020']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2019' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2019']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2018' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2018']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 ) 
        elif '2017' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2017']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2016' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2016']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2015' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2015']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2014' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2014']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 ) 
        elif '2013' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2013']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2012' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2012']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2011' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2011']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2010' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2010']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2009' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2009']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 ) 
        elif '2008' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2008']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2007' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2007']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2006' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2006']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )
        elif '2005' in v :
            if n2 in list( file_slam_data.iloc[ dict_years['2005']-anni_prima, list( dict_placements[ LABEL_PLACE ] ) ] ):
                lista_raccolta_2.append( 1 )
            else :
                lista_raccolta_2.append( 0 )

In [5]:
def diff_somm( lista_raccolta_1, lista_raccolta_2, lista_diff, lista_plus ) :
    for idx, v in enumerate ( lista_raccolta_1 ) :
        diff = v - lista_raccolta_2[idx]
        plus = v + lista_raccolta_2[idx]
        lista_diff.append( diff )
        lista_plus.append( plus )

In [6]:
def desc_master_1000( lista_partite, file_slam_data, lista_raccolta_1,
                      lista_raccolta_2, anni_prima, LABEL_PLACE,
                      lista_diff, lista_plus ) :
    print("Running descriptor...")
    ricerca_stringa_in_dataframe_name1( lista_partite, file_slam_data, lista_raccolta_1, anni_prima, LABEL_PLACE )
    ricerca_stringa_in_dataframe_name2( lista_partite, file_slam_data, lista_raccolta_2, anni_prima, LABEL_PLACE )
    diff_somm( lista_raccolta_1, lista_raccolta_2, lista_diff, lista_plus )
    print("DONE")

# LAST YEAR

In [7]:
# CAMBIARE ANNI PRECEDENTI FUNZIONI

n1_Top50 = []
n2_Top50 = []
diff_Top50 = []
plus_Top50 = []

desc_master_1000( partite, file_master_1000_data, n1_Top50,
                  n2_Top50, 1, "Top50", diff_Top50, plus_Top50 )

n1_Top40 = []
n2_Top40 = []
diff_Top40 = []
plus_Top40 = []

desc_master_1000( partite, file_master_1000_data, n1_Top40,
                  n2_Top40, 1, "Top40", diff_Top40, plus_Top40 )

n1_Top30 = []
n2_Top30 = []
diff_Top30 = []
plus_Top30 = []

desc_master_1000( partite, file_master_1000_data, n1_Top30,
                  n2_Top30, 1, "Top30", diff_Top30, plus_Top30 )

n1_Top25 = []
n2_Top25 = []
diff_Top25 = []
plus_Top25 = []

desc_master_1000( partite, file_master_1000_data, n1_Top25,
                  n2_Top25, 1, "Top25", diff_Top25, plus_Top25 )

n1_Top20 = []
n2_Top20 = []
diff_Top20 = []
plus_Top20 = []

desc_master_1000( partite, file_master_1000_data, n1_Top20,
                  n2_Top20, 1, "Top20", diff_Top20, plus_Top20 )

n1_Top15 = []
n2_Top15 = []
diff_Top15 = []
plus_Top15 = []

desc_master_1000( partite, file_master_1000_data, n1_Top15,
                  n2_Top15, 1, "Top15", diff_Top15, plus_Top15 )

n1_Top10 = []
n2_Top10 = []
diff_Top10 = []
plus_Top10 = []

desc_master_1000( partite, file_master_1000_data, n1_Top10,
                  n2_Top10, 1, "Top10", diff_Top10, plus_Top10 )

n1_Top5 = []
n2_Top5 = []
diff_Top5 = []
plus_Top5 = []

desc_master_1000( partite, file_master_1000_data, n1_Top5,
                  n2_Top5, 1, "Top5", diff_Top5, plus_Top5 )

# CAMBIARE ANNI PRECEDENTI TITOLO DATAFRAME
anni_precedenti = 1

# CAMBIARE TITOLO DATAFRAME
desc_last_year = pd.DataFrame()
desc_last_year['PARTITE'] = partite
desc_last_year[str( anni_precedenti )+'diff_Top50'] = diff_Top50
#desc_last_year[str( anni_precedenti )+'plus_Top50'] = plus_Top50
desc_last_year[str( anni_precedenti )+'diff_Top40'] = diff_Top40
#desc_last_year[str( anni_precedenti )+'plus_Top40'] = plus_Top40
desc_last_year[str( anni_precedenti )+'diff_Top30'] = diff_Top30
#desc_last_year[str( anni_precedenti )+'plus_Top30'] = plus_Top30
desc_last_year[str( anni_precedenti )+'diff_Top25'] = diff_Top25
#desc_last_year[str( anni_precedenti )+'plus_Top25'] = plus_Top25
desc_last_year[str( anni_precedenti )+'diff_Top20'] = diff_Top20
#desc_last_year[str( anni_precedenti )+'plus_Top20'] = plus_Top20
desc_last_year[str( anni_precedenti )+'diff_Top15'] = diff_Top15
#desc_last_year[str( anni_precedenti )+'plus_Top15'] = plus_Top15
desc_last_year[str( anni_precedenti )+'diff_Top10'] = diff_Top10
#desc_last_year[str( anni_precedenti )+'plus_Top10'] = plus_Top10
desc_last_year[str( anni_precedenti )+'diff_Top5'] = diff_Top5
#desc_last_year[str( anni_precedenti )+'plus_Top5'] = plus_Top5
desc_last_year

Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE

,PARTITE,1diff_Top50,1diff_Top40,1diff_Top30,1diff_Top25,1diff_Top20,1diff_Top15,1diff_Top10,1diff_Top5
1830,QRT_GROSJEAN_DAVYDENKO_3_DOHA_2005_HARD_,0,0,0,1,1,1,0,0
1831,F_LJUBICIC_FEDERER_3_DOHA_2005_HARD_,0,0,0,0,-1,-1,-1,-1
1832,SF_DAVYDENKO_FEDERER_3_DOHA_2005_HARD_,0,0,0,-1,-1,-1,-1,-1
1833,SF_COSTA_LJUBICIC_3_DOHA_2005_HARD_,-1,-1,-1,-1,0,0,0,0
1834,QRT_SANTORO_COSTA_3_DOHA_2005_HARD_,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
14365,QRT_ISNER_O'CONNELL_3_ATLANTA_2021_HARD,1,1,1,1,0,0,0,0
14366,SF_NAKASHIMA_RUUSUVUORI_3_ATLANTA_2021_HARD,0,0,0,0,0,0,0,0
14367,SF_ISNER_FRITZ_3_ATLANTA_2021_HARD,0,0,0,1,0,0,0,0
14368,F_ISNER_NAKASHIMA_3_ATLANTA_2021_HARD,1,1,1,1,0,0,0,0
14369,SF_RUUSUVUORI_NAKASHIMA_3_ATLANTA_2021_HARD_,0,0,0,0,0,0,0,0

# 2 YEARS AGO

In [8]:
# CAMBIARE ANNI PRECEDENTI FUNZIONI

n1_Top50 = []
n2_Top50 = []
diff_Top50 = []
plus_Top50 = []

desc_master_1000( partite, file_master_1000_data, n1_Top50,
                  n2_Top50, 2, "Top50", diff_Top50, plus_Top50 )

n1_Top40 = []
n2_Top40 = []
diff_Top40 = []
plus_Top40 = []

desc_master_1000( partite, file_master_1000_data, n1_Top40,
                  n2_Top40, 2, "Top40", diff_Top40, plus_Top40 )

n1_Top30 = []
n2_Top30 = []
diff_Top30 = []
plus_Top30 = []

desc_master_1000( partite, file_master_1000_data, n1_Top30,
                  n2_Top30, 2, "Top30", diff_Top30, plus_Top30 )

n1_Top25 = []
n2_Top25 = []
diff_Top25 = []
plus_Top25 = []

desc_master_1000( partite, file_master_1000_data, n1_Top25,
                  n2_Top25, 2, "Top25", diff_Top25, plus_Top25 )

n1_Top20 = []
n2_Top20 = []
diff_Top20 = []
plus_Top20 = []

desc_master_1000( partite, file_master_1000_data, n1_Top20,
                  n2_Top20, 2, "Top20", diff_Top20, plus_Top20 )

n1_Top15 = []
n2_Top15 = []
diff_Top15 = []
plus_Top15 = []

desc_master_1000( partite, file_master_1000_data, n1_Top15,
                  n2_Top15, 2, "Top15", diff_Top15, plus_Top15 )

n1_Top10 = []
n2_Top10 = []
diff_Top10 = []
plus_Top10 = []

desc_master_1000( partite, file_master_1000_data, n1_Top10,
                  n2_Top10, 2, "Top10", diff_Top10, plus_Top10 )

n1_Top5 = []
n2_Top5 = []
diff_Top5 = []
plus_Top5 = []

desc_master_1000( partite, file_master_1000_data, n1_Top5,
                  n2_Top5, 2, "Top5", diff_Top5, plus_Top5 )

# CAMBIARE ANNI PRECEDENTI TITOLO DATAFRAME
anni_precedenti = 2

# CAMBIARE TITOLO DATAFRAME
desc_2_years_ago = pd.DataFrame()
desc_2_years_ago['PARTITE'] = partite
desc_2_years_ago[str( anni_precedenti )+'diff_Top50'] = diff_Top50
#desc_2_years_ago[str( anni_precedenti )+'plus_Top50'] = plus_Top50
desc_2_years_ago[str( anni_precedenti )+'diff_Top40'] = diff_Top40
#desc_2_years_ago[str( anni_precedenti )+'plus_Top40'] = plus_Top40
desc_2_years_ago[str( anni_precedenti )+'diff_Top30'] = diff_Top30
#desc_2_years_ago[str( anni_precedenti )+'plus_Top30'] = plus_Top30
desc_2_years_ago[str( anni_precedenti )+'diff_Top25'] = diff_Top25
#desc_2_years_ago[str( anni_precedenti )+'plus_Top25'] = plus_Top25
desc_2_years_ago[str( anni_precedenti )+'diff_Top20'] = diff_Top20
#desc_2_years_ago[str( anni_precedenti )+'plus_Top20'] = plus_Top20
desc_2_years_ago[str( anni_precedenti )+'diff_Top15'] = diff_Top15
#desc_2_years_ago[str( anni_precedenti )+'plus_Top15'] = plus_Top15
desc_2_years_ago[str( anni_precedenti )+'diff_Top10'] = diff_Top10
#desc_2_years_ago[str( anni_precedenti )+'plus_Top10'] = plus_Top10
desc_2_years_ago[str( anni_precedenti )+'diff_Top5'] = diff_Top5
#desc_2_years_ago[str( anni_precedenti )+'plus_Top5'] = plus_Top5
desc_2_years_ago

Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE

,PARTITE,2diff_Top50,2diff_Top40,2diff_Top30,2diff_Top25,2diff_Top20,2diff_Top15,2diff_Top10,2diff_Top5
1830,QRT_GROSJEAN_DAVYDENKO_3_DOHA_2005_HARD_,0,1,1,1,1,1,1,0
1831,F_LJUBICIC_FEDERER_3_DOHA_2005_HARD_,0,-1,-1,-1,-1,-1,-1,-1
1832,SF_DAVYDENKO_FEDERER_3_DOHA_2005_HARD_,0,-1,-1,-1,-1,-1,-1,-1
1833,SF_COSTA_LJUBICIC_3_DOHA_2005_HARD_,0,1,1,1,0,0,0,0
1834,QRT_SANTORO_COSTA_3_DOHA_2005_HARD_,-1,-1,-1,-1,0,0,0,0
...,...,...,...,...,...,...,...,...,...
14365,QRT_ISNER_O'CONNELL_3_ATLANTA_2021_HARD,1,1,1,1,1,0,0,0
14366,SF_NAKASHIMA_RUUSUVUORI_3_ATLANTA_2021_HARD,0,0,0,0,0,0,0,0
14367,SF_ISNER_FRITZ_3_ATLANTA_2021_HARD,0,0,1,1,1,0,0,0
14368,F_ISNER_NAKASHIMA_3_ATLANTA_2021_HARD,1,1,1,1,1,0,0,0
14369,SF_RUUSUVUORI_NAKASHIMA_3_ATLANTA_2021_HARD_,0,0,0,0,0,0,0,0

# 3 YEARS AGO

In [9]:
# CAMBIARE ANNI PRECEDENTI FUNZIONI

n1_Top50 = []
n2_Top50 = []
diff_Top50 = []
plus_Top50 = []

desc_master_1000( partite, file_master_1000_data, n1_Top50,
                  n2_Top50, 3, "Top50", diff_Top50, plus_Top50 )

n1_Top40 = []
n2_Top40 = []
diff_Top40 = []
plus_Top40 = []

desc_master_1000( partite, file_master_1000_data, n1_Top40,
                  n2_Top40, 3, "Top40", diff_Top40, plus_Top40 )

n1_Top30 = []
n2_Top30 = []
diff_Top30 = []
plus_Top30 = []

desc_master_1000( partite, file_master_1000_data, n1_Top30,
                  n2_Top30, 3, "Top30", diff_Top30, plus_Top30 )

n1_Top25 = []
n2_Top25 = []
diff_Top25 = []
plus_Top25 = []

desc_master_1000( partite, file_master_1000_data, n1_Top25,
                  n2_Top25, 3, "Top25", diff_Top25, plus_Top25 )

n1_Top20 = []
n2_Top20 = []
diff_Top20 = []
plus_Top20 = []

desc_master_1000( partite, file_master_1000_data, n1_Top20,
                  n2_Top20, 3, "Top20", diff_Top20, plus_Top20 )

n1_Top15 = []
n2_Top15 = []
diff_Top15 = []
plus_Top15 = []

desc_master_1000( partite, file_master_1000_data, n1_Top15,
                  n2_Top15, 3, "Top15", diff_Top15, plus_Top15 )

n1_Top10 = []
n2_Top10 = []
diff_Top10 = []
plus_Top10 = []

desc_master_1000( partite, file_master_1000_data, n1_Top10,
                  n2_Top10, 3, "Top10", diff_Top10, plus_Top10 )

n1_Top5 = []
n2_Top5 = []
diff_Top5 = []
plus_Top5 = []

desc_master_1000( partite, file_master_1000_data, n1_Top5,
                  n2_Top5, 3, "Top5", diff_Top5, plus_Top5 )

# CAMBIARE ANNI PRECEDENTI TITOLO DATAFRAME
anni_precedenti = 3

# CAMBIARE TITOLO DATAFRAME
desc_3_years_ago = pd.DataFrame()
desc_3_years_ago['PARTITE'] = partite
desc_3_years_ago[str( anni_precedenti )+'diff_Top50'] = diff_Top50
#desc_3_years_ago[str( anni_precedenti )+'plus_Top50'] = plus_Top50
desc_3_years_ago[str( anni_precedenti )+'diff_Top40'] = diff_Top40
#desc_3_years_ago[str( annius_Top25
desc_3_years_ago[str( anni_precedenti )+'diff_Top30'] = diff_Top30
#desc_3_years_ago[str( anni_precedenti )+'plus_Top30'] = plus_Top30
desc_3_years_ago[str( anni_precedenti )+'diff_Top25'] = diff_Top25
#desc_3_years_ago[str( anni_precedenti )+'plus_Top25'] = plus_Top25
desc_3_years_ago[str( anni_precedenti )+'diff_Top20'] = diff_Top20
#desc_3_years_ago[str( anni_precedenti )+'plus_Top20'] = plus_Top20
desc_3_years_ago[str( anni_precedenti )+'diff_Top15'] = diff_Top15
#desc_3_years_ago[str( anni_precedenti )+'plus_Top15'] = plus_Top15
desc_3_years_ago[str( anni_precedenti )+'diff_Top10'] = diff_Top10
#desc_3_years_ago[str( anni_precedenti )+'plus_Top10'] = plus_Top10
desc_3_years_ago[str( anni_precedenti )+'diff_Top5'] = diff_Top5
#desc_3_years_ago[str( anni_precedenti )+'plus_Top5'] = plus_Top5
desc_3_years_ago

Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE
Running descriptor...
DONE

,PARTITE,3diff_Top50,3diff_Top40,3diff_Top30,3diff_Top25,3diff_Top20,3diff_Top15,3diff_Top10,3diff_Top5
1830,QRT_GROSJEAN_DAVYDENKO_3_DOHA_2005_HARD_,1,1,1,1,1,0,0,0
1831,F_LJUBICIC_FEDERER_3_DOHA_2005_HARD_,0,-1,-1,-1,-1,-1,-1,0
1832,SF_DAVYDENKO_FEDERER_3_DOHA_2005_HARD_,-1,-1,-1,-1,-1,-1,-1,0
1833,SF_COSTA_LJUBICIC_3_DOHA_2005_HARD_,0,1,1,1,1,1,1,0
1834,QRT_SANTORO_COSTA_3_DOHA_2005_HARD_,0,0,-1,-1,-1,-1,-1,0
...,...,...,...,...,...,...,...,...,...
14365,QRT_ISNER_O'CONNELL_3_ATLANTA_2021_HARD,1,1,1,1,1,1,1,0
14366,SF_NAKASHIMA_RUUSUVUORI_3_ATLANTA_2021_HARD,0,0,0,0,0,0,0,0
14367,SF_ISNER_FRITZ_3_ATLANTA_2021_HARD,0,1,1,1,1,1,1,0
14368,F_ISNER_NAKASHIMA_3_ATLANTA_2021_HARD,1,1,1,1,1,1,1,0
14369,SF_RUUSUVUORI_NAKASHIMA_3_ATLANTA_2021_HARD_,0,0,0,0,0,0,0,0

In [10]:
master_data = desc_last_year.merge( desc_2_years_ago, on='PARTITE' )
master_data = master_data.merge( desc_3_years_ago, on='PARTITE' )
master_data

,PARTITE,1diff_Top50,1diff_Top40,1diff_Top30,1diff_Top25,1diff_Top20,1diff_Top15,1diff_Top10,1diff_Top5,2diff_Top50,...,2diff_Top10,2diff_Top5,3diff_Top50,3diff_Top40,3diff_Top30,3diff_Top25,3diff_Top20,3diff_Top15,3diff_Top10,3diff_Top5
0,QRT_GROSJEAN_DAVYDENKO_3_DOHA_2005_HARD_,0,0,0,1,1,1,0,0,0,...,1,0,1,1,1,1,1,0,0,0
1,F_LJUBICIC_FEDERER_3_DOHA_2005_HARD_,0,0,0,0,-1,-1,-1,-1,0,...,-1,-1,0,-1,-1,-1,-1,-1,-1,0
2,SF_DAVYDENKO_FEDERER_3_DOHA_2005_HARD_,0,0,0,-1,-1,-1,-1,-1,0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,0
3,SF_COSTA_LJUBICIC_3_DOHA_2005_HARD_,-1,-1,-1,-1,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,0
4,QRT_SANTORO_COSTA_3_DOHA_2005_HARD_,0,0,0,0,0,0,0,0,-1,...,0,0,0,0,-1,-1,-1,-1,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12535,QRT_ISNER_O'CONNELL_3_ATLANTA_2021_HARD,1,1,1,1,0,0,0,0,1,...,0,0,1,1,1,1,1,1,1,0
12536,SF_NAKASHIMA_RUUSUVUORI_3_ATLANTA_2021_HARD,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12537,SF_ISNER_FRITZ_3_ATLANTA_2021_HARD,0,0,0,1,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,0
12538,F_ISNER_NAKASHIMA_3_ATLANTA_2021_HARD,1,1,1,1,0,0,0,0,1,...,0,0,1,1,1,1,1,1,1,0
12539,SF_RUUSUVUORI_NAKASHIMA_3_ATLANTA_2021_HARD_,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
master_data.to_excel( stringa_nome_excel )