In [1]:
import pandas as pd
import numpy as np


file_partite = 'data_totale_CLAY.xlsx'
file_partite_read = pd.read_excel( file_partite )
file_partite_data = pd.DataFrame( file_partite_read )
file_partite_data


file_date_tornei = 'dataframe_interesse_CLAY.xlsx'
file_date_tornei_read = pd.read_excel( file_date_tornei )
file_date_tornei_data = pd.DataFrame( file_date_tornei_read )

In [2]:
file_partite_data

,unicode,PARTITE,set_p1,set_p2,games_1_set1,games_1_set2,games_1_set3,games_2_set1,games_2_set2,games_2_set3,segno
0,0,F_FERRERO_MOYA_3_MonteCARLO_2002_CLAY,3,0,7,6,6,5,3,4,1
1,1,SF_MOYA_HENMAN_3_MonteCARLO_2002_CLAY,2,1,6,5,6,4,7,3,1
2,2,SF_FERRERO_GROSJEAN_3_MonteCARLO_2002_CLAY,2,1,6,1,6,3,6,0,1
3,3,QRT_MOYA_SAFIN_3_MonteCARLO_2002_CLAY,2,1,6,2,7,1,6,6,1
4,4,QRT_HENMAN_JOHANSSON_3_MonteCARLO_2002_CLAY,2,1,2,6,7,6,4,6,1
...,...,...,...,...,...,...,...,...,...,...,...
2305,2305,OTT_ALIASSIME_DELBONIS_3_ROME_2021_CLAY_,0,2,63,1,,7,6,,2
2306,2306,OTT_SHAPOVALOV_NADAL_3_ROME_2021_CLAY_,1,2,6,4,63,3,6,7,2
2307,2307,OTT_BERRETTINI_TSITSIPAS_3_ROME_2021_CLAY_,0,2,63,2,,7,6,,2
2308,2308,OTT_FOKINA_DJOKOVIC_3_ROME_2021_CLAY_,0,2,2,1,,6,6,,2
2309,2309,OTT_KARATSEV_OPELKA_3_ROME_2021_CLAY_,0,2,66,4,,7,6,,2

In [3]:
file_date_tornei_data

    Unnamed: 0            tornei        data data_parsed UNICODE_LOCATIONS
0          137       Monte Carlo  16.04.2002  2002-04-16        MonteCARLO
1          134         Barcelona  23.04.2002  2002-04-23         BARCELONA
2          127              Rome  07.05.2002  2002-05-07              ROME
3           25  Madrid - Masters  14.10.2002  2002-10-14            MADRID
4          354       Monte Carlo  14.04.2003  2003-04-14        MonteCARLO
..         ...               ...         ...         ...               ...
75        4373              Rome  14.09.2020  2020-09-14              ROME
76        4657       Monte Carlo  11.04.2021  2021-04-11        MonteCARLO
77        4649         Barcelona  19.04.2021  2021-04-19         BARCELONA
78        4643  Madrid - Masters  02.05.2021  2021-05-02            MADRID
79        4639              Rome  09.05.2021  2021-05-09              ROME

[80 rows x 5 columns]

In [4]:
data_parsed_partite = []
conto = 0

for idx, v in enumerate ( file_partite_data.PARTITE ):
    for ind, val in enumerate ( file_date_tornei_data.UNICODE_LOCATIONS ):
            locat = v.split("_")[4]
            date_partita = v.split("_")[5]
            if locat==val :
                if date_partita in file_date_tornei_data.data[ind]:
                    data_parsed_partite.append( file_date_tornei_data.data_parsed[ind] )
            

                    
print( len( data_parsed_partite ))            
print( data_parsed_partite )

2310

In [5]:
data_parsed_partite = pd.Series( data_parsed_partite )
conti = data_parsed_partite.value_counts()

for v in conti :
    print( v )

30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30

In [6]:
file_partite_data['data_parsed'] = data_parsed_partite

file_partite_data

,unicode,PARTITE,set_p1,set_p2,games_1_set1,games_1_set2,games_1_set3,games_2_set1,games_2_set2,games_2_set3,segno,data_parsed
0,0,F_FERRERO_MOYA_3_MonteCARLO_2002_CLAY,3,0,7,6,6,5,3,4,1,2002-04-16
1,1,SF_MOYA_HENMAN_3_MonteCARLO_2002_CLAY,2,1,6,5,6,4,7,3,1,2002-04-16
2,2,SF_FERRERO_GROSJEAN_3_MonteCARLO_2002_CLAY,2,1,6,1,6,3,6,0,1,2002-04-16
3,3,QRT_MOYA_SAFIN_3_MonteCARLO_2002_CLAY,2,1,6,2,7,1,6,6,1,2002-04-16
4,4,QRT_HENMAN_JOHANSSON_3_MonteCARLO_2002_CLAY,2,1,2,6,7,6,4,6,1,2002-04-16
...,...,...,...,...,...,...,...,...,...,...,...,...
2305,2305,OTT_ALIASSIME_DELBONIS_3_ROME_2021_CLAY_,0,2,63,1,,7,6,,2,2021-05-09
2306,2306,OTT_SHAPOVALOV_NADAL_3_ROME_2021_CLAY_,1,2,6,4,63,3,6,7,2,2021-05-09
2307,2307,OTT_BERRETTINI_TSITSIPAS_3_ROME_2021_CLAY_,0,2,63,2,,7,6,,2,2021-05-09
2308,2308,OTT_FOKINA_DJOKOVIC_3_ROME_2021_CLAY_,0,2,2,1,,6,6,,2,2021-05-09
2309,2309,OTT_KARATSEV_OPELKA_3_ROME_2021_CLAY_,0,2,66,4,,7,6,,2,2021-05-09

In [7]:
print( len( file_partite_data.PARTITE ) )

2310

In [8]:
file_partite_data

,unicode,PARTITE,set_p1,set_p2,games_1_set1,games_1_set2,games_1_set3,games_2_set1,games_2_set2,games_2_set3,segno,data_parsed
0,0,F_FERRERO_MOYA_3_MonteCARLO_2002_CLAY,3,0,7,6,6,5,3,4,1,2002-04-16
1,1,SF_MOYA_HENMAN_3_MonteCARLO_2002_CLAY,2,1,6,5,6,4,7,3,1,2002-04-16
2,2,SF_FERRERO_GROSJEAN_3_MonteCARLO_2002_CLAY,2,1,6,1,6,3,6,0,1,2002-04-16
3,3,QRT_MOYA_SAFIN_3_MonteCARLO_2002_CLAY,2,1,6,2,7,1,6,6,1,2002-04-16
4,4,QRT_HENMAN_JOHANSSON_3_MonteCARLO_2002_CLAY,2,1,2,6,7,6,4,6,1,2002-04-16
...,...,...,...,...,...,...,...,...,...,...,...,...
2305,2305,OTT_ALIASSIME_DELBONIS_3_ROME_2021_CLAY_,0,2,63,1,,7,6,,2,2021-05-09
2306,2306,OTT_SHAPOVALOV_NADAL_3_ROME_2021_CLAY_,1,2,6,4,63,3,6,7,2,2021-05-09
2307,2307,OTT_BERRETTINI_TSITSIPAS_3_ROME_2021_CLAY_,0,2,63,2,,7,6,,2,2021-05-09
2308,2308,OTT_FOKINA_DJOKOVIC_3_ROME_2021_CLAY_,0,2,2,1,,6,6,,2,2021-05-09
2309,2309,OTT_KARATSEV_OPELKA_3_ROME_2021_CLAY_,0,2,66,4,,7,6,,2,2021-05-09

In [9]:
file_partite_data.to_excel("file_partite_data_parsed_CLAY.xlsx")