In [11]:
import pandas as pd
import numpy as np


file_partite = 'data_totale_GRASS.xlsx'
file_partite_read = pd.read_excel( file_partite )
file_partite_data = pd.DataFrame( file_partite_read )
file_partite_data


file_date_tornei = 'dataframe_interesse_GRASS.xlsx'
file_date_tornei_read = pd.read_excel( file_date_tornei )
file_date_tornei_data = pd.DataFrame( file_date_tornei_read )

In [12]:
file_partite_data

,unicode,PARTITE,set_p1,set_p2,games_1_set1,games_1_set2,games_1_set3,games_2_set1,games_2_set2,games_2_set3,segno
0,0,F_YOUZHNY_CANAS_3_STOCCARDA_2002_GRASS,3,2,6,3,3,3,6,6,1
1,1,SF_CANAS_NOVAK_3_STOCCARDA_2002_GRASS,2,0,6,6,,4,0,,1
2,2,SF_YOUZHNY_BURGSMULLER_3_STOCCARDA_2002_GRASS,2,1,6,4,7,3,6,5,1
3,3,QRT_NOVAK_ROBREDO_3_STOCCARDA_2002_GRASS,2,0,6,6,,4,2,,1
4,4,QRT_CANAS_MARTIN_3_STOCCARDA_2002_GRASS,2,1,1,6,7,6,2,6,1
...,...,...,...,...,...,...,...,...,...,...,...
1705,1705,OTT_NISHIKORI_KORDA_3_HALLE_2021_GRASS_,1,2,6,3,5,2,6,7,2
1706,1706,OTT_STRUFF_GIRON_3_HALLE_2021_GRASS_,1,2,7,3,4,61,6,6,2
1707,1707,OTT_FEDERER_ALIASSIME_3_HALLE_2021_GRASS_,1,2,6,3,2,4,6,6,2
1708,1708,OTT_THOMPSON_RUBLEV_3_HALLE_2021_GRASS_,0,2,4,4,,6,6,,2
1709,1709,OTT_MOUTET_KOHLSCHREIBER_3_HALLE_2021_GRASS_,0,2,4,64,,6,7,,2

In [13]:
file_date_tornei_data

    Unnamed: 0        tornei        data data_parsed UNICODE_LOCATIONS
0          109  Queen's Club  10.06.2002  2002-06-10            QUEENS
1          108         Halle  10.06.2002  2002-06-10             HALLE
2           86     Stuttgart  15.07.2002  2002-07-15         STOCCARDA
3          314         Halle  09.06.2003  2003-06-09             HALLE
4          315  Queen's Club  09.06.2003  2003-06-09            QUEENS
5          290     Stuttgart  14.07.2003  2003-07-14         STOCCARDA
6          536  Queen's Club  07.06.2004  2004-06-07            QUEENS
7          535         Halle  07.06.2004  2004-06-07             HALLE
8          510     Stuttgart  12.07.2004  2004-07-12         STOCCARDA
9          755  Queen's Club  06.06.2005  2005-06-06            QUEENS
10         754         Halle  06.06.2005  2005-06-06             HALLE
11         727     Stuttgart  18.07.2005  2005-07-18         STOCCARDA
12         989         Halle  12.06.2006  2006-06-12             HALLE
13         990  Queen's Club  12.06.2006  2006-06-12            QUEENS
14         960     Stuttgart  17.07.2006  2006-07-17         STOCCARDA
15        1245  Queen's Club  11.06.2007  2007-06-11            QUEENS
16        1244         Halle  11.06.2007  2007-06-11             HALLE
17        1214     Stuttgart  16.07.2007  2007-07-16         STOCCARDA
18        1504         Halle  09.06.2008  2008-06-09             HALLE
19        1505  Queen's Club  09.06.2008  2008-06-09            QUEENS
20        1481     Stuttgart  07.07.2008  2008-07-07         STOCCARDA
21        1758         Halle  08.06.2009  2009-06-08             HALLE
22        1759  Queen's Club  08.06.2009  2009-06-08            QUEENS
23        1733     Stuttgart  13.07.2009  2009-07-13         STOCCARDA
24        2012  Queen's Club  07.06.2010  2010-06-07            QUEENS
25        2011         Halle  07.06.2010  2010-06-07             HALLE
26        1990     Stuttgart  12.07.2010  2010-07-12         STOCCARDA
27        2253         Halle  06.06.2011  2011-06-06             HALLE
28        2252  Queen's Club  06.06.2011  2011-06-06            QUEENS
29        2233     Stuttgart  11.07.2011  2011-07-11         STOCCARDA
30        2489         Halle  11.06.2012  2012-06-11             HALLE
31        2488  Queen's Club  12.06.2012  2012-06-12            QUEENS
32        2469     Stuttgart  09.07.2012  2012-07-09         STOCCARDA
33        2732  Queen's Club  10.06.2013  2013-06-10            QUEENS
34        2731         Halle  10.06.2013  2013-06-10             HALLE
35        2710     Stuttgart  08.07.2013  2013-07-08         STOCCARDA
36        2956         Halle  09.06.2014  2014-06-09             HALLE
37        2957  Queen's Club  09.06.2014  2014-06-09            QUEENS
38        2937     Stuttgart  07.07.2014  2014-07-07         STOCCARDA
39        3208     Stuttgart  08.06.2015  2015-06-08         STOCCARDA
40        3201         Halle  15.06.2015  2015-06-15             HALLE
41        3202  Queen's Club  15.06.2015  2015-06-15            QUEENS
42        3465     Stuttgart  06.06.2016  2016-06-06         STOCCARDA
43        3460         Halle  13.06.2016  2016-06-13             HALLE
44        3459  Queen's Club  13.06.2016  2016-06-13            QUEENS
45        3719     Stuttgart  12.06.2017  2017-06-12         STOCCARDA
46        3712         Halle  19.06.2017  2017-06-19             HALLE
47        3713  Queen's Club  19.06.2017  2017-06-19            QUEENS
48        3959     Stuttgart  11.06.2018  2018-06-11         STOCCARDA
49        3953  Queen's Club  18.06.2018  2018-06-18            QUEENS
50        3952         Halle  18.06.2018  2018-06-18             HALLE
51        4211     Stuttgart  10.06.2019  2019-06-10         STOCCARDA
52        4203         Halle  17.06.2019  2019-06-17             HALLE
53        4204  Queen's Club  17.06.2019  2019-06-17            QUEENS
54        4480     Stuttgart  08.06.2020  2020-06-08         STOCCARDA
55        4471  Queen's Club  15.06.2020  2020-06-15            QUEENS
56        4470         Halle  15.06.2020  2020-06-15             HALLE
57        4604     Stuttgart  08.06.2021  2021-06-08         STOCCARDA
58        4597         Halle  14.06.2021  2021-06-14             HALLE
59        4598  Queen's Club  14.06.2021  2021-06-14            QUEENS

In [14]:
data_parsed_partite = []
conto = 0

for idx, v in enumerate ( file_partite_data.PARTITE ):
    for ind, val in enumerate ( file_date_tornei_data.UNICODE_LOCATIONS ):
            locat = v.split("_")[4]
            date_partita = v.split("_")[5]
            if locat==val :
                if date_partita in file_date_tornei_data.data[ind]:
                    data_parsed_partite.append( file_date_tornei_data.data_parsed[ind] )
            

                    
print( len( data_parsed_partite ))            
print( data_parsed_partite )

1710

In [15]:
data_parsed_partite = pd.Series( data_parsed_partite )
conti = data_parsed_partite.value_counts()

for v in conti :
    print( v )

60
60
60
60
60
60
60
60
60
60
60
60
60
60
60
60
60
60
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30

In [16]:
file_partite_data['data_parsed'] = data_parsed_partite

file_partite_data

,unicode,PARTITE,set_p1,set_p2,games_1_set1,games_1_set2,games_1_set3,games_2_set1,games_2_set2,games_2_set3,segno,data_parsed
0,0,F_YOUZHNY_CANAS_3_STOCCARDA_2002_GRASS,3,2,6,3,3,3,6,6,1,2002-07-15
1,1,SF_CANAS_NOVAK_3_STOCCARDA_2002_GRASS,2,0,6,6,,4,0,,1,2002-07-15
2,2,SF_YOUZHNY_BURGSMULLER_3_STOCCARDA_2002_GRASS,2,1,6,4,7,3,6,5,1,2002-07-15
3,3,QRT_NOVAK_ROBREDO_3_STOCCARDA_2002_GRASS,2,0,6,6,,4,2,,1,2002-07-15
4,4,QRT_CANAS_MARTIN_3_STOCCARDA_2002_GRASS,2,1,1,6,7,6,2,6,1,2002-07-15
...,...,...,...,...,...,...,...,...,...,...,...,...
1705,1705,OTT_NISHIKORI_KORDA_3_HALLE_2021_GRASS_,1,2,6,3,5,2,6,7,2,2021-06-14
1706,1706,OTT_STRUFF_GIRON_3_HALLE_2021_GRASS_,1,2,7,3,4,61,6,6,2,2021-06-14
1707,1707,OTT_FEDERER_ALIASSIME_3_HALLE_2021_GRASS_,1,2,6,3,2,4,6,6,2,2021-06-14
1708,1708,OTT_THOMPSON_RUBLEV_3_HALLE_2021_GRASS_,0,2,4,4,,6,6,,2,2021-06-14
1709,1709,OTT_MOUTET_KOHLSCHREIBER_3_HALLE_2021_GRASS_,0,2,4,64,,6,7,,2,2021-06-14

In [17]:
print( len( file_partite_data.PARTITE ) )

1710

In [18]:
file_partite_data = file_partite_data.sort_values( by='data_parsed')

In [19]:
file_partite_data

,unicode,PARTITE,set_p1,set_p2,games_1_set1,games_1_set2,games_1_set3,games_2_set1,games_2_set2,games_2_set3,segno,data_parsed
1147,1147,OTT_POPP_KOUBEK_3_HALLE_2002_GRASS,2,0,6,6,,4,2,,1,2002-06-10
1435,1435,OTT_PAVEL_YOUZHNY_3_HALLE_2002_GRASS_,0,2,4,0,,6,6,,2,2002-06-10
1436,1436,OTT_SCHUETTLER_ULIHRACH_3_HALLE_2002_GRASS_,1,2,2,7,5,6,6,7,2,2002-06-10
1437,1437,OTT_KRATOCHVIL_CARLSEN_3_HALLE_2002_GRASS_,1,2,6,4,4,3,6,6,2,2002-06-10
1438,1438,OTT_SAULNIER_KAFELNIKOV_3_HALLE_2002_GRASS_,0,2,3,5,,6,7,,2,2002-06-10
...,...,...,...,...,...,...,...,...,...,...,...,...
1135,1135,OTT_MANNARINO_EVANS_3_QUEENS_2021_GRASS_,0,2,4,67,,6,7,,2,2021-06-14
1134,1134,OTT_MURRAY_BERRETTINI_3_QUEENS_2021_GRASS_,0,2,3,3,,6,6,,2,2021-06-14
1133,1133,OTT_LOPEZ_SHAPOVALOV_3_QUEENS_2021_GRASS_,0,2,2,3,,6,6,,2,2021-06-14
1412,1412,SF_RUBLEV_BASILASHVILI_3_HALLE_2021_GRASS,2,1,6,3,6,1,6,3,1,2021-06-14
1709,1709,OTT_MOUTET_KOHLSCHREIBER_3_HALLE_2021_GRASS_,0,2,4,64,,6,7,,2,2021-06-14

In [20]:
file_partite_data.to_excel("file_partite_data_parsed_GRASS_NOgames.xlsx")