In [1]:
import pandas as pd
import numpy as np

file_stoccarda = 'stoccarda_from2002.xlsx'
file_queens = 'queens_from2002.xlsx'
file_halle = 'halle_from2002.xlsx'

In [2]:
lista_file_aggiunti = [file_stoccarda, file_queens,
                       file_halle ]

lista_dataframes = []

for f in lista_file_aggiunti:
    data_agg = pd.read_excel( f )
    data_agg = pd.DataFrame( data_agg )
    lista_dataframes.append( data_agg )
    
data_totale = pd.concat( lista_dataframes )
data_totale

,Unnamed: 0,PARTITE,set_p1,set_p2,games_1_set1,games_1_set2,games_1_set3,games_2_set1,games_2_set2,games_2_set3,segno
0,0,F_YOUZHNY_CANAS_3_STOCCARDA_2002_GRASS,3,2,6,3,3,3,6,6,1
1,1,SF_CANAS_NOVAK_3_STOCCARDA_2002_GRASS,2,0,6,6,,4,0,,1
2,2,SF_YOUZHNY_BURGSMULLER_3_STOCCARDA_2002_GRASS,2,1,6,4,7,3,6,5,1
3,3,QRT_NOVAK_ROBREDO_3_STOCCARDA_2002_GRASS,2,0,6,6,,4,2,,1
4,4,QRT_CANAS_MARTIN_3_STOCCARDA_2002_GRASS,2,1,1,6,7,6,2,6,1
...,...,...,...,...,...,...,...,...,...,...,...
565,280,OTT_NISHIKORI_KORDA_3_HALLE_2021_GRASS_,1,2,6,3,5,2,6,7,2
566,281,OTT_STRUFF_GIRON_3_HALLE_2021_GRASS_,1,2,7,3,4,61,6,6,2
567,282,OTT_FEDERER_ALIASSIME_3_HALLE_2021_GRASS_,1,2,6,3,2,4,6,6,2
568,283,OTT_THOMPSON_RUBLEV_3_HALLE_2021_GRASS_,0,2,4,4,,6,6,,2
569,284,OTT_MOUTET_KOHLSCHREIBER_3_HALLE_2021_GRASS_,0,2,4,64,,6,7,,2

In [3]:
unicode = []
conto = -1
for idx, v in enumerate ( data_totale.PARTITE ):
    conto = conto+1
    unicode.append( conto )

data_totale['unicode'] = unicode 
data_totale = data_totale.set_index("unicode")
data_totale = data_totale.iloc[:,1:]
data_totale

,PARTITE,set_p1,set_p2,games_1_set1,games_1_set2,games_1_set3,games_2_set1,games_2_set2,games_2_set3,segno
unicode,,,,,,,,,,
0,F_YOUZHNY_CANAS_3_STOCCARDA_2002_GRASS,3,2,6,3,3,3,6,6,1
1,SF_CANAS_NOVAK_3_STOCCARDA_2002_GRASS,2,0,6,6,,4,0,,1
2,SF_YOUZHNY_BURGSMULLER_3_STOCCARDA_2002_GRASS,2,1,6,4,7,3,6,5,1
3,QRT_NOVAK_ROBREDO_3_STOCCARDA_2002_GRASS,2,0,6,6,,4,2,,1
4,QRT_CANAS_MARTIN_3_STOCCARDA_2002_GRASS,2,1,1,6,7,6,2,6,1
...,...,...,...,...,...,...,...,...,...,...
1705,OTT_NISHIKORI_KORDA_3_HALLE_2021_GRASS_,1,2,6,3,5,2,6,7,2
1706,OTT_STRUFF_GIRON_3_HALLE_2021_GRASS_,1,2,7,3,4,61,6,6,2
1707,OTT_FEDERER_ALIASSIME_3_HALLE_2021_GRASS_,1,2,6,3,2,4,6,6,2
1708,OTT_THOMPSON_RUBLEV_3_HALLE_2021_GRASS_,0,2,4,4,,6,6,,2
1709,OTT_MOUTET_KOHLSCHREIBER_3_HALLE_2021_GRASS_,0,2,4,64,,6,7,,2

In [4]:
data_totale_meno_dubbie = data_totale
data_totale_meno_dubbie

,PARTITE,set_p1,set_p2,games_1_set1,games_1_set2,games_1_set3,games_2_set1,games_2_set2,games_2_set3,segno
unicode,,,,,,,,,,
0,F_YOUZHNY_CANAS_3_STOCCARDA_2002_GRASS,3,2,6,3,3,3,6,6,1
1,SF_CANAS_NOVAK_3_STOCCARDA_2002_GRASS,2,0,6,6,,4,0,,1
2,SF_YOUZHNY_BURGSMULLER_3_STOCCARDA_2002_GRASS,2,1,6,4,7,3,6,5,1
3,QRT_NOVAK_ROBREDO_3_STOCCARDA_2002_GRASS,2,0,6,6,,4,2,,1
4,QRT_CANAS_MARTIN_3_STOCCARDA_2002_GRASS,2,1,1,6,7,6,2,6,1
...,...,...,...,...,...,...,...,...,...,...
1705,OTT_NISHIKORI_KORDA_3_HALLE_2021_GRASS_,1,2,6,3,5,2,6,7,2
1706,OTT_STRUFF_GIRON_3_HALLE_2021_GRASS_,1,2,7,3,4,61,6,6,2
1707,OTT_FEDERER_ALIASSIME_3_HALLE_2021_GRASS_,1,2,6,3,2,4,6,6,2
1708,OTT_THOMPSON_RUBLEV_3_HALLE_2021_GRASS_,0,2,4,4,,6,6,,2
1709,OTT_MOUTET_KOHLSCHREIBER_3_HALLE_2021_GRASS_,0,2,4,64,,6,7,,2

In [5]:
data_totale_meno_dubbie.to_excel("data_totale_GRASS.xlsx")

In [6]:
lista_posti = []
for v in data_totale_meno_dubbie.PARTITE:
    s = v.split("_")[4]
    lista_posti.append( s )
    
lista_posti = pd.Series( lista_posti )
print( lista_posti.unique() )

['STOCCARDA' 'QUEENS' 'HALLE']